/**
 * AI Compliance Scanner - LLM Analysis Service
 * 
 * This service uses Large Language Models (GPT-4/Claude) to analyze
 * scraped website content for compliance gaps and generate actionable reports.
 */

import { supabase } from '../lib/supabaseClient';
import { ScrapedPage } from './complianceScraperService';

// ============================================================================
// TYPES
// ============================================================================

export interface ComplianceAnalysisRequest {
  scanId: string;
  companyName: string;
  domain: string;
  industry?: string;
  pages: ScrapedPage[];
  detectedTechnologies: string[];
}

export interface ComplianceAnalysisResult {
  success: boolean;
  overallRiskScore: number;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  categories: ComplianceCategory[];
  complianceStatus: {
    gdpr: ComplianceStatus;
    ccpa: ComplianceStatus;
    aiAct: ComplianceStatus;
  };
  detectedIntegrations: string[];
  missingPolicies: string[];
  summary: string;
  error?: string;
}

export interface ComplianceCategory {
  category: string;
  subcategory?: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  score: number;
  title: string;
  description: string;
  evidence: string[];
  sourceUrls: string[];
  recommendations: string[];
  fixDifficulty: 'easy' | 'moderate' | 'complex' | 'requires-legal';
  estimatedFixTime: string;
  gdprArticles?: string[];
  ccpaSections?: string[];
  aiActReferences?: string[];
  isBlocking: boolean;
  isEnforced: boolean;
  fineRisk?: string;
  suggestedPolicyText?: string;
}

interface ComplianceStatus {
  compliant: boolean;
  score: number;
  issues: string[];
}

// ============================================================================
// COMPLIANCE RUBRIC
// ============================================================================

const COMPLIANCE_RUBRIC = {
  ai_disclosure: {
    weight: 0.25,
    checks: [
      {
        id: 'ai_001',
        title: 'AI/ML Use Disclosure',
        description: 'Service must clearly disclose use of AI/ML technologies',
        severity: 'high' as const,
        keywords: ['AI', 'artificial intelligence', 'machine learning', 'automated', 'algorithm'],
        gdprArticles: ['Article 13', 'Article 14'],
      },
      {
        id: 'ai_002',
        title: 'AI-Generated Content Labeling',
        description: 'AI-generated outputs must be labeled as synthetic',
        severity: 'medium' as const,
        keywords: ['generated by', 'AI-created', 'synthetic', 'automated content'],
      },
      {
        id: 'ai_003',
        title: 'AI Limitations Disclosure',
        description: 'Limitations and potential errors of AI systems must be disclosed',
        severity: 'medium' as const,
        keywords: ['may contain errors', 'limitations', 'accuracy', 'not guaranteed'],
      },
      {
        id: 'ai_004',
        title: 'Human Oversight Mention',
        description: 'Explain if human review is available for AI decisions',
        severity: 'high' as const,
        keywords: ['human review', 'human oversight', 'human intervention', 'human decision'],
        aiActReferences: ['Article 14'],
      },
    ],
  },
  gdpr_privacy: {
    weight: 0.30,
    checks: [
      {
        id: 'gdpr_001',
        title: 'Privacy Policy Existence',
        description: 'Website must have an accessible privacy policy',
        severity: 'critical' as const,
        gdprArticles: ['Article 12', 'Article 13', 'Article 14'],
      },
      {
        id: 'gdpr_002',
        title: 'Data Retention Period',
        description: 'Privacy policy must specify data retention periods',
        severity: 'high' as const,
        keywords: ['retain', 'retention period', 'delete after', 'keep for', 'storage period'],
        gdprArticles: ['Article 5(1)(e)', 'Article 13(2)(a)'],
      },
      {
        id: 'gdpr_003',
        title: 'Data Subject Rights',
        description: 'Must explain user rights (access, deletion, portability, etc.)',
        severity: 'high' as const,
        keywords: ['your rights', 'access your data', 'delete your data', 'data portability', 'right to erasure'],
        gdprArticles: ['Articles 15-22'],
      },
      {
        id: 'gdpr_004',
        title: 'Legal Basis for Processing',
        description: 'Must specify legal basis for data processing',
        severity: 'high' as const,
        keywords: ['legal basis', 'lawful basis', 'consent', 'legitimate interest', 'contractual necessity'],
        gdprArticles: ['Article 6'],
      },
      {
        id: 'gdpr_005',
        title: 'Third-Party Processors',
        description: 'Must list third-party data processors and sub-processors',
        severity: 'medium' as const,
        keywords: ['third party', 'third-party', 'processors', 'sub-processors', 'service providers'],
        gdprArticles: ['Article 28'],
      },
      {
        id: 'gdpr_006',
        title: 'EU Representative',
        description: 'Non-EU companies processing EU data must appoint an EU representative',
        severity: 'high' as const,
        keywords: ['EU representative', 'European representative', 'Article 27', 'representative in the EU'],
        gdprArticles: ['Article 27'],
      },
      {
        id: 'gdpr_007',
        title: 'Data Protection Officer Contact',
        description: 'DPO contact information if applicable',
        severity: 'medium' as const,
        keywords: ['data protection officer', 'DPO', 'privacy officer', 'data controller'],
        gdprArticles: ['Articles 37-39'],
      },
      {
        id: 'gdpr_008',
        title: 'International Data Transfers',
        description: 'Must explain safeguards for data transfers outside EU/EEA',
        severity: 'high' as const,
        keywords: ['data transfer', 'international transfer', 'standard contractual clauses', 'adequacy decision', 'Privacy Shield'],
        gdprArticles: ['Articles 44-46'],
      },
    ],
  },
  ccpa_privacy: {
    weight: 0.20,
    checks: [
      {
        id: 'ccpa_001',
        title: 'Notice at Collection',
        description: 'Must provide notice at or before data collection',
        severity: 'high' as const,
        keywords: ['notice at collection', 'categories of information', 'purposes for collection'],
        ccpaSections: ['§1798.100(a)', '§1798.100(b)'],
      },
      {
        id: 'ccpa_002',
        title: 'Do Not Sell Link',
        description: 'Must provide "Do Not Sell My Personal Information" link if selling data',
        severity: 'high' as const,
        keywords: ['do not sell', 'opt-out of sale', 'selling personal information'],
        ccpaSections: ['§1798.120', '§1798.135'],
      },
      {
        id: 'ccpa_003',
        title: 'Data Deletion Right',
        description: 'Must honor consumer requests to delete personal information',
        severity: 'high' as const,
        keywords: ['delete your information', 'deletion request', 'right to delete'],
        ccpaSections: ['§1798.105'],
      },
      {
        id: 'ccpa_004',
        title: 'Categories of Data Collected',
        description: 'Must disclose categories of personal information collected',
        severity: 'medium' as const,
        keywords: ['categories of information', 'types of data', 'personal information collected'],
        ccpaSections: ['§1798.110'],
      },
    ],
  },
  consent_management: {
    weight: 0.10,
    checks: [
      {
        id: 'consent_001',
        title: 'Cookie Consent Banner',
        description: 'Must obtain consent before placing non-essential cookies',
        severity: 'medium' as const,
        keywords: ['cookie consent', 'accept cookies', 'cookie banner', 'cookie notice'],
      },
      {
        id: 'consent_002',
        title: 'Opt-in/Opt-out Mechanisms',
        description: 'Must provide clear opt-in or opt-out options',
        severity: 'medium' as const,
        keywords: ['opt-in', 'opt-out', 'unsubscribe', 'consent', 'preferences'],
      },
      {
        id: 'consent_003',
        title: 'Granular Consent Options',
        description: 'Should allow users to consent to specific processing activities',
        severity: 'low' as const,
        keywords: ['manage preferences', 'consent options', 'cookie settings', 'privacy preferences'],
      },
    ],
  },
  data_security: {
    weight: 0.10,
    checks: [
      {
        id: 'security_001',
        title: 'Security Measures Disclosure',
        description: 'Must describe security measures protecting user data',
        severity: 'medium' as const,
        keywords: ['security measures', 'encryption', 'secure', 'protect your data', 'data security'],
        gdprArticles: ['Article 32'],
      },
      {
        id: 'security_002',
        title: 'Breach Notification Policy',
        description: 'Must explain data breach notification procedures',
        severity: 'medium' as const,
        keywords: ['data breach', 'security incident', 'breach notification', 'notify you'],
        gdprArticles: ['Articles 33-34'],
      },
    ],
  },
  ai_act_high_risk: {
    weight: 0.05,
    checks: [
      {
        id: 'aiact_001',
        title: 'Biometric Data Processing',
        description: 'High-risk: Processing biometric data for identification',
        severity: 'critical' as const,
        keywords: ['biometric', 'facial recognition', 'fingerprint', 'voice recognition', 'iris scan'],
        aiActReferences: ['Annex III, Point 1'],
      },
      {
        id: 'aiact_002',
        title: 'Emotion Recognition',
        description: 'High-risk: Systems that detect emotions',
        severity: 'high' as const,
        keywords: ['emotion detection', 'sentiment analysis', 'mood detection', 'emotional state'],
        aiActReferences: ['Article 5(1)(f)'],
      },
      {
        id: 'aiact_003',
        title: 'Automated Decision Making',
        description: 'High-risk: Automated decisions with legal/significant effects',
        severity: 'high' as const,
        keywords: ['automated decision', 'algorithmic decision', 'AI decision', 'without human intervention'],
        gdprArticles: ['Article 22'],
        aiActReferences: ['Annex III'],
      },
    ],
  },
};

// ============================================================================
// MAIN ANALYSIS FUNCTION
// ============================================================================

/**
 * Analyze compliance using LLM
 */
export async function analyzeCompliance(request: ComplianceAnalysisRequest): Promise<ComplianceAnalysisResult> {
  console.log(`[Analyzer] Starting compliance analysis for ${request.companyName}`);
  
  try {
    // Update scan status
    await updateScanStatus(request.scanId, 'analyzing');
    
    // 1. Prepare content for analysis
    const content = prepareContentForAnalysis(request.pages);
    
    // 2. Run LLM analysis
    const llmResult = await runLLMAnalysis(request, content);
    
    // 3. Calculate risk scores
    const riskScores = calculateRiskScores(llmResult.categories);
    
    // 4. Determine compliance status
    const complianceStatus = determineComplianceStatus(llmResult.categories);
    
    // 5. Save findings to database
    await saveFindingsToDatabase(request.scanId, llmResult.categories);
    
    // 6. Update scan with final results
    await updateScanWithResults(request.scanId, riskScores, complianceStatus);
    
    const result: ComplianceAnalysisResult = {
      success: true,
      overallRiskScore: riskScores.overall,
      riskLevel: riskScores.level,
      categories: llmResult.categories,
      complianceStatus,
      detectedIntegrations: request.detectedTechnologies,
      missingPolicies: llmResult.missingPolicies,
      summary: llmResult.summary,
    };
    
    console.log(`[Analyzer] Analysis complete. Risk score: ${riskScores.overall}/10 (${riskScores.level})`);
    
    return result;
    
  } catch (error) {
    console.error(`[Analyzer] Analysis failed:`, error);
    await updateScanStatus(request.scanId, 'failed', error instanceof Error ? error.message : 'Analysis error');
    
    return {
      success: false,
      overallRiskScore: 0,
      riskLevel: 'low',
      categories: [],
      complianceStatus: {
        gdpr: { compliant: false, score: 0, issues: [] },
        ccpa: { compliant: false, score: 0, issues: [] },
        aiAct: { compliant: false, score: 0, issues: [] },
      },
      detectedIntegrations: [],
      missingPolicies: [],
      summary: 'Analysis failed',
      error: error instanceof Error ? error.message : 'Unknown analysis error',
    };
  }
}

// ============================================================================
// LLM ANALYSIS
// ============================================================================

interface LLMAnalysisResult {
  categories: ComplianceCategory[];
  missingPolicies: string[];
  summary: string;
}

/**
 * Run LLM-based compliance analysis
 * This uses OpenAI's GPT-4 or Anthropic's Claude via API
 */
async function runLLMAnalysis(
  request: ComplianceAnalysisRequest,
  content: PreparedContent
): Promise<LLMAnalysisResult> {
  
  // In production, you would call OpenAI or Anthropic API here
  // For now, we'll use a rule-based analysis with the rubric
  
  const categories: ComplianceCategory[] = [];
  
  // Analyze each category in the rubric
  for (const [categoryKey, categoryConfig] of Object.entries(COMPLIANCE_RUBRIC)) {
    for (const check of categoryConfig.checks) {
      const finding = analyzeCheck(check, content, request);
      if (finding) {
        categories.push(finding);
      }
    }
  }
  
  // Determine missing policies
  const missingPolicies: string[] = [];
  if (!content.hasPrivacyPolicy) missingPolicies.push('Privacy Policy');
  if (!content.hasTerms) missingPolicies.push('Terms of Service');
  if (request.detectedTechnologies.some(tech => tech.includes('cookie')) && !content.hasCookiePolicy) {
    missingPolicies.push('Cookie Policy');
  }
  
  // Generate summary
  const criticalCount = categories.filter(c => c.severity === 'critical').length;
  const highCount = categories.filter(c => c.severity === 'high').length;
  
  let summary = `Found ${categories.length} compliance issues`;
  if (criticalCount > 0) {
    summary += ` including ${criticalCount} critical issue${criticalCount > 1 ? 's' : ''}`;
  }
  if (highCount > 0) {
    summary += ` and ${highCount} high-priority issue${highCount > 1 ? 's' : ''}`;
  }
  summary += `.`;
  
  if (missingPolicies.length > 0) {
    summary += ` Missing policies: ${missingPolicies.join(', ')}.`;
  }
  
  return {
    categories,
    missingPolicies,
    summary,
  };
}

interface PreparedContent {
  homepage: string;
  privacyPolicy: string;
  terms: string;
  other: string;
  hasPrivacyPolicy: boolean;
  hasTerms: boolean;
  hasCookiePolicy: boolean;
  allText: string;
}

/**
 * Prepare scraped content for analysis
 */
function prepareContentForAnalysis(pages: ScrapedPage[]): PreparedContent {
  const content: PreparedContent = {
    homepage: '',
    privacyPolicy: '',
    terms: '',
    other: '',
    hasPrivacyPolicy: false,
    hasTerms: false,
    hasCookiePolicy: false,
    allText: '',
  };
  
  for (const page of pages) {
    const text = page.parsedText;
    
    switch (page.pageType) {
      case 'homepage':
        content.homepage = text;
        break;
      case 'privacy':
        content.privacyPolicy = text;
        content.hasPrivacyPolicy = true;
        break;
      case 'terms':
        content.terms = text;
        content.hasTerms = true;
        break;
      case 'cookies':
        content.hasCookiePolicy = true;
        content.other += text + '\n\n';
        break;
      default:
        content.other += text + '\n\n';
    }
    
    content.allText += text + '\n\n';
  }
  
  return content;
}

/**
 * Analyze a single compliance check
 */
function analyzeCheck(
  check: any,
  content: PreparedContent,
  request: ComplianceAnalysisRequest
): ComplianceCategory | null {
  
  // Determine which content to search
  let searchText = content.allText;
  if (check.id.startsWith('gdpr_') || check.id.startsWith('ccpa_')) {
    searchText = content.privacyPolicy || content.terms || content.allText;
  } else if (check.id.startsWith('ai_')) {
    searchText = content.homepage + ' ' + content.terms + ' ' + content.privacyPolicy;
  }
  
  // Check for keywords if specified
  if (check.keywords) {
    const hasKeywords = check.keywords.some((keyword: string) =>
      searchText.toLowerCase().includes(keyword.toLowerCase())
    );
    
    if (hasKeywords) {
      // Found evidence - this check passes
      return null;
    }
  }
  
  // Special checks
  if (check.id === 'gdpr_001' && !content.hasPrivacyPolicy) {
    return createFinding(check, request, [], 'No privacy policy found');
  }
  
  if (check.id === 'ai_001' && request.detectedTechnologies.some(tech => 
    ['openai', 'anthropic', 'cohere', 'huggingface'].includes(tech)
  )) {
    // Uses AI but no disclosure
    const hasAIDisclosure = check.keywords.some((keyword: string) =>
      searchText.toLowerCase().includes(keyword.toLowerCase())
    );
    
    if (!hasAIDisclosure) {
      return createFinding(
        check,
        request,
        [`Detected AI technology (${request.detectedTechnologies.join(', ')}) but no disclosure found`],
        'AI use detected without proper disclosure'
      );
    }
  }
  
  // If keywords specified but not found, this is a potential issue
  if (check.keywords && check.keywords.length > 0) {
    return createFinding(check, request, [], `Required language not found in policy`);
  }
  
  return null;
}

/**
 * Create a compliance finding
 */
function createFinding(
  check: any,
  request: ComplianceAnalysisRequest,
  evidence: string[],
  description: string
): ComplianceCategory {
  
  // Generate recommendations
  const recommendations = generateRecommendations(check, request);
  
  // Calculate score (inverse of severity)
  const severityScores = {
    critical: 10,
    high: 8,
    medium: 5,
    low: 3,
  };
  
  const score = severityScores[check.severity as keyof typeof severityScores] || 5;
  
  return {
    category: check.id.split('_')[0],
    subcategory: check.id,
    severity: check.severity,
    score,
    title: check.title,
    description: description || check.description,
    evidence,
    sourceUrls: [],
    recommendations,
    fixDifficulty: check.severity === 'critical' ? 'requires-legal' : 
                   check.severity === 'high' ? 'moderate' : 'easy',
    estimatedFixTime: check.severity === 'critical' ? '1-2 weeks' :
                      check.severity === 'high' ? '2-5 days' :
                      check.severity === 'medium' ? '1-2 days' : '1-4 hours',
    gdprArticles: check.gdprArticles || [],
    ccpaSections: check.ccpaSections || [],
    aiActReferences: check.aiActReferences || [],
    isBlocking: check.severity === 'critical',
    isEnforced: check.severity === 'critical' || check.severity === 'high',
    fineRisk: check.severity === 'critical' ? 'Up to €20M or 4% of revenue (GDPR)' : undefined,
  };
}

/**
 * Generate recommendations for a check
 */
function generateRecommendations(check: any, request: ComplianceAnalysisRequest): string[] {
  const recommendations: string[] = [];
  
  // Check-specific recommendations
  if (check.id === 'gdpr_001') {
    recommendations.push('Create a comprehensive privacy policy following GDPR Article 13 requirements');
    recommendations.push('Include sections on data collection, use, retention, and user rights');
    recommendations.push('Make the policy easily accessible from your homepage (footer link)');
  } else if (check.id === 'ai_001') {
    recommendations.push('Add an "AI Use Disclosure" section to your Terms of Service or Privacy Policy');
    recommendations.push('Example: "This service uses AI and machine learning to [describe functionality]"');
    recommendations.push('Disclose which data is processed by AI systems');
  } else if (check.id === 'gdpr_002') {
    recommendations.push('Specify data retention periods for each category of data');
    recommendations.push('Example: "User account data is retained for 90 days after account deletion"');
  } else if (check.id === 'gdpr_003') {
    recommendations.push('Add a "Your Rights" section explaining GDPR rights (access, deletion, portability, etc.)');
    recommendations.push('Provide a contact method for users to exercise their rights');
  } else if (check.id === 'gdpr_006') {
    recommendations.push('Appoint an EU representative if you process data of EU residents');
    recommendations.push('Include representative contact details in your privacy policy');
  } else if (check.id === 'ccpa_002') {
    recommendations.push('If you sell personal information, add a "Do Not Sell My Personal Information" link');
    recommendations.push('Add the link to your website footer for easy access');
  } else {
    // Generic recommendation
    recommendations.push(`Update your privacy policy to address: ${check.title}`);
    if (check.keywords && check.keywords.length > 0) {
      recommendations.push(`Include language related to: ${check.keywords.slice(0, 3).join(', ')}`);
    }
  }
  
  // Add reference to regulations
  if (check.gdprArticles && check.gdprArticles.length > 0) {
    recommendations.push(`Reference: GDPR ${check.gdprArticles.join(', ')}`);
  }
  if (check.ccpaSections && check.ccpaSections.length > 0) {
    recommendations.push(`Reference: CCPA ${check.ccpaSections.join(', ')}`);
  }
  
  return recommendations;
}

// ============================================================================
// RISK SCORING
// ============================================================================

interface RiskScores {
  overall: number;
  level: 'low' | 'medium' | 'high' | 'critical';
  byCategory: Record<string, number>;
}

/**
 * Calculate overall risk scores
 */
function calculateRiskScores(categories: ComplianceCategory[]): RiskScores {
  if (categories.length === 0) {
    return {
      overall: 0,
      level: 'low',
      byCategory: {},
    };
  }
  
  const byCategory: Record<string, number> = {};
  
  // Group by category and calculate weighted average
  for (const category of categories) {
    if (!byCategory[category.category]) {
      byCategory[category.category] = 0;
    }
    byCategory[category.category] += category.score;
  }
  
  // Average scores per category
  const categoryCount: Record<string, number> = {};
  for (const category of categories) {
    categoryCount[category.category] = (categoryCount[category.category] || 0) + 1;
  }
  
  for (const cat in byCategory) {
    byCategory[cat] = byCategory[cat] / categoryCount[cat];
  }
  
  // Calculate weighted overall score
  let weightedSum = 0;
  let totalWeight = 0;
  
  for (const [categoryKey, categoryConfig] of Object.entries(COMPLIANCE_RUBRIC)) {
    if (byCategory[categoryKey]) {
      weightedSum += byCategory[categoryKey] * categoryConfig.weight;
      totalWeight += categoryConfig.weight;
    }
  }
  
  const overall = totalWeight > 0 ? weightedSum / totalWeight : 0;
  
  // Determine risk level
  let level: 'low' | 'medium' | 'high' | 'critical';
  if (overall >= 8) level = 'critical';
  else if (overall >= 6) level = 'high';
  else if (overall >= 4) level = 'medium';
  else level = 'low';
  
  return {
    overall: Math.round(overall * 10) / 10, // Round to 1 decimal
    level,
    byCategory,
  };
}

/**
 * Determine compliance status by jurisdiction
 */
function determineComplianceStatus(categories: ComplianceCategory[]): {
  gdpr: ComplianceStatus;
  ccpa: ComplianceStatus;
  aiAct: ComplianceStatus;
} {
  const gdprIssues = categories.filter(c => 
    c.category === 'gdpr' || c.gdprArticles && c.gdprArticles.length > 0
  );
  const ccpaIssues = categories.filter(c => 
    c.category === 'ccpa' || c.ccpaSections && c.ccpaSections.length > 0
  );
  const aiActIssues = categories.filter(c => 
    c.category === 'aiact' || c.aiActReferences && c.aiActReferences.length > 0
  );
  
  return {
    gdpr: {
      compliant: gdprIssues.length === 0,
      score: gdprIssues.length === 0 ? 10 : Math.max(0, 10 - gdprIssues.length * 2),
      issues: gdprIssues.map(i => i.title),
    },
    ccpa: {
      compliant: ccpaIssues.length === 0,
      score: ccpaIssues.length === 0 ? 10 : Math.max(0, 10 - ccpaIssues.length * 2),
      issues: ccpaIssues.map(i => i.title),
    },
    aiAct: {
      compliant: aiActIssues.length === 0,
      score: aiActIssues.length === 0 ? 10 : Math.max(0, 10 - aiActIssues.length * 3),
      issues: aiActIssues.map(i => i.title),
    },
  };
}

// ============================================================================
// DATABASE OPERATIONS
// ============================================================================

/**
 * Save findings to database
 */
async function saveFindingsToDatabase(scanId: string, categories: ComplianceCategory[]): Promise<void> {
  const records = categories.map(category => ({
    scan_id: scanId,
    category: category.category,
    subcategory: category.subcategory,
    severity: category.severity,
    score: category.score,
    title: category.title,
    description: category.description,
    evidence: category.evidence,
    source_urls: category.sourceUrls,
    recommendations: category.recommendations,
    fix_difficulty: category.fixDifficulty,
    estimated_fix_time: category.estimatedFixTime,
    gdpr_articles: category.gdprArticles,
    ccpa_sections: category.ccpaSections,
    ai_act_references: category.aiActReferences,
    is_blocking: category.isBlocking,
    is_enforced: category.isEnforced,
    fine_risk_amount: category.fineRisk,
    suggested_policy_text: category.suggestedPolicyText,
  }));
  
  const { error } = await supabase
    .from('compliance_findings')
    .insert(records);
  
  if (error) {
    console.error('[Analyzer] Failed to save findings:', error);
    throw error;
  }
  
  console.log(`[Analyzer] Saved ${categories.length} findings to database`);
}

/**
 * Update scan with final results
 */
async function updateScanWithResults(
  scanId: string,
  riskScores: RiskScores,
  complianceStatus: any
): Promise<void> {
  const updates = {
    status: 'complete',
    completed_at: new Date().toISOString(),
    overall_risk_score: riskScores.overall,
    risk_level: riskScores.level,
    gdpr_compliant: complianceStatus.gdpr.compliant,
    gdpr_score: complianceStatus.gdpr.score,
    ccpa_compliant: complianceStatus.ccpa.compliant,
    ccpa_score: complianceStatus.ccpa.score,
    ai_act_compliant: complianceStatus.aiAct.compliant,
    ai_act_score: complianceStatus.aiAct.score,
  };
  
  const { error } = await supabase
    .from('compliance_scans')
    .update(updates)
    .eq('id', scanId);
  
  if (error) {
    console.error('[Analyzer] Failed to update scan:', error);
    throw error;
  }
}

/**
 * Update scan status
 */
async function updateScanStatus(
  scanId: string,
  status: string,
  errorMessage?: string
): Promise<void> {
  const updates: any = {
    status,
    updated_at: new Date().toISOString(),
  };
  
  if (status === 'analyzing') {
    updates.analyzing_started_at = new Date().toISOString();
  }
  
  if (errorMessage) {
    updates.error_message = errorMessage;
  }
  
  const { error } = await supabase
    .from('compliance_scans')
    .update(updates)
    .eq('id', scanId);
  
  if (error) {
    console.error('[Analyzer] Failed to update scan status:', error);
  }
}

// ============================================================================
// EXPORT
// ============================================================================

export { COMPLIANCE_RUBRIC };

